---
# tasks file for ansible-observium
- import_tasks: set_facts.yml

- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: install.yml

- import_tasks: config.yml

- import_tasks: users.yml

- import_tasks: cron.yml
